version: "3.4"
services:
  api:
    container_name: ceii_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ ceii_db ]
    ports:
      - "5050:80"
  ceii_db:
    container_name: ceii_db
    image: "mcr.microsoft.com/mssql/server"
    hostname: mssql
    environment:
      SA_PASSWORD: "HAKNCEA1209-3uasdia"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "11433:1433"